<a href="https://colab.research.google.com/github/jacobbstephen/ML_Programs/blob/main/Soil_Fertility.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection  import train_test_split
from sklearn.metrics import mean_squared_error, accuracy_score, confusion_matrix, classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

from sklearn.preprocessing import LabelEncoder,  MinMaxScaler
import matplotlib.pyplot as plt

In [4]:
data = pd.read_csv('/content/soil_fertility.csv')

In [5]:
data.head()

N    P    K    pH    EC    OC     S    Zn    Fe    Cu    Mn     B  Output
0  138  8.6  560  7.46  0.62  0.70   5.9  0.24  0.31  0.77  8.71  0.11       0
1  213  7.5  338  7.62  0.75  1.06  25.4  0.30  0.86  1.54  2.89  2.29       0
2  163  9.6  718  7.59  0.51  1.11  14.3  0.30  0.86  1.57  2.70  2.03       0
3  157  6.8  475  7.64  0.58  0.94  26.0  0.34  0.54  1.53  2.65  1.82       0
4  270  9.9  444  7.63  0.40  0.86  11.8  0.25  0.76  1.69  2.43  2.26       1

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 880 entries, 0 to 879
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   N       880 non-null    int64  
 1   P       880 non-null    float64
 2   K       880 non-null    int64  
 3   pH      880 non-null    float64
 4   EC      880 non-null    float64
 5   OC      880 non-null    float64
 6   S       880 non-null    float64
 7   Zn      880 non-null    float64
 8   Fe      880 non-null    float64
 9   Cu      880 non-null    float64
 10  Mn      880 non-null    float64
 11  B       880 non-null    float64
 12  Output  880 non-null    int64  
dtypes: float64(10), int64(3)
memory usage: 89.5 KB


In [7]:
data['Output'].value_counts()

Output
1    440
0    401
2     39
Name: count, dtype: int64

In [ ]:
#Class fertility (0 "Less Fertile", 1 "Fertile", 2 "Highly Fertile")


CLASS IMBALANCE- SMOTENN

In [8]:
from imblearn.combine import SMOTEENN
X = data.drop('Output', axis=1)
Y = data['Output']
X_resampled, Y_resampled = SMOTEENN().fit_resample(X, Y)


In [9]:
Y_resampled.value_counts()

Output
2    366
0    333
1    236
Name: count, dtype: int64

In [10]:
# split training and test data
X_train, X_test, Y_train, Y_test = train_test_split(X_resampled, Y_resampled, test_size=0.2, random_state=42)

In [12]:
rfc = RandomForestClassifier(random_state=42)
rfc.fit(X_train, Y_train)
y_test_pred = rfc.predict(X_test)
print("Accuracy Score:\n", accuracy_score(Y_test, y_test_pred))
print("Confsuion Matrix:\n", confusion_matrix(Y_test, y_test_pred))
print("Classification Report:\n", classification_report(Y_test, y_test_pred))

Accuracy Score:
 0.9893048128342246
Confsuion Matrix:
 [[71  0  0]
 [ 0 45  1]
 [ 0  1 69]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        71
           1       0.98      0.98      0.98        46
           2       0.99      0.99      0.99        70

    accuracy                           0.99       187
   macro avg       0.99      0.99      0.99       187
weighted avg       0.99      0.99      0.99       187



In [13]:
y_train_pred = rfc.predict(X_train)

print("Accuracy Score:\n", accuracy_score(Y_train, y_train_pred))
print("Confsuion Matrix:\n", confusion_matrix(Y_train, y_train_pred))
print("Classification Report:\n", classification_report(Y_train, y_train_pred))

Accuracy Score:
 1.0
Confsuion Matrix:
 [[262   0   0]
 [  0 190   0]
 [  0   0 296]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       262
           1       1.00      1.00      1.00       190
           2       1.00      1.00      1.00       296

    accuracy                           1.00       748
   macro avg       1.00      1.00      1.00       748
weighted avg       1.00      1.00      1.00       748



In [16]:
input_data = [333, 14.9, 422, 8.26, 0.48, 1.17, 3.32, 0.6, 7.62, 1.02, 11.65, 0.29]
sample = np.array(input_data).reshape(1, -1)
prediction = rfc.predict(sample)
print(prediction)

[2]


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
